# ==============================================================================
# Inventario AMT generado automáticamente para AWX / Ansible (Por Clientes)
# Fecha: 2026-09-28 15:36:31
# Total: 153 servidores (Linux: 72, Windows: 81) en 9 Clientes
# ==============================================================================

# ==============================================================================
# 1. GRUPOS POR CLIENTE
# ==============================================================================

[ATH]
ath-app1-1 ansible_host=100.65.46.208
ath-app1-2 ansible_host=100.123.15.248

[AVVILLAS]
sv-villa-1-1 ansible_host=100.123.15.30
sv-villa-2-1 ansible_host=100.123.15.131

[EL_TIEMPO]
ANTHOLOGY1 ansible_host=10.61.0.1
ANTHOLOGY2 ansible_host=10.61.0.1
ANTHOLOGY2 ansible_host=10.61.0.4
CACTUS1 ansible_host=10.61.2.7
CENTAURI ansible_host=10.61.1.16

[HOTELES_ESTELAR]
HEY0028 ansible_host=100.65.40.104

[PCCAS]
apploadbalancebta11 ansible_host=100.123.15.112
apploadbalancebta21 ansible_host=100.123.15.111
CIMWAS1-1 ansible_host=10.250.100.165
CIMWAS1-1 ansible_host=100.123.15.106
CIMWAS2-2 ansible_host=100.123.15.109
cm-was-bancobog1-1 ansible_host=100.123.14.119
cm-was-bancobog2-1 ansible_host=100.123.14.120
cm-was-ccc1-1 ansible_host=100.123.15.99
cm-was-ccc2-1 ansible_host=100.123.15.98
cm-was-GVP-aval-1-1 ansible_host=100.123.14.183
cm-was-gvp-aval-1-2 ansible_host=100.123.14.184
cm-was-gvp-aval-1-3 ansible_host=100.123.14.185
cm-was-GVP-aval-2-1 ansible_host=172.18.9.113
cm-was-GVP-aval-2-2 ansible_host=172.18.9.114
cm-was-GVP-aval-2-3 ansible_host=100.123.15.90
cm-was-gvp-ivr-banco-bogota-1-1 ansible_host=100.123.15.100
cm-was-gvp-ivr-banco-bogota-2-1 ansible_host=100.123.15.101
cm-was-ORS-aval-1-1 ansible_host=100.123.14.28
cm-was-ORS-aval-1-2 ansible_host=100.123.14.27
cm-was-ORS-aval-1-3 ansible_host=100.123.15.91
cm-was-ORS-aval-2-1 ansible_host=100.123.14.36
cm-was-ORS-aval-2-2 ansible_host=100.123.14.169
cm-was-ORS-aval-2-3 ansible_host=100.123.15.91
desarrollos1 ansible_host=100.65.33.99
desarrollos2 ansible_host=100.65.33.100
desarrollos2 ansible_host=100.66.33.100
FILESERVER1 ansible_host=10.250.100.134
FILESERVER2 ansible_host=10.250.100.135
FORMULARIOSSERVER1 ansible_host=172.27.181.101
FORMULARIOSSERVER2 ansible_host=172.27.181.102
GADMIN1-1 ansible_host=10.110.43.132
GIM1-2-TFM1301 ansible_host=10.250.100.155
GIM2-2-TFM1307 ansible_host=10.250.100.163
GMS1-1 ansible_host=10.250.100.205
GMS1-3 ansible_host=100.123.15.102
GMS2-1 ansible_host=10.250.100.203
GMS2-3 ansible_host=100.123.15.103
gvpwas1-1 ansible_host=100.123.15.104
gvpwas2-1 ansible_host=100.123.15.105
HTCC1_1 ansible_host=10.250.100.172
HTCC1_2 ansible_host=10.250.100.173
HTCC2_1 ansible_host=10.250.100.174
LABMCPGIR1 ansible_host=172.27.181.99
OMH0043_Tomcat ansible_host=10.110.52.174
PRCIMWAS1-1 ansible_host=10.250.100.171
SPOTLIGHT ansible_host=172.27.184.195
TFM3053 ansible_host=172.27.181.100
WFM1-1 ansible_host=10.250.100.200
WFM1-2 ansible_host=10.250.100.158
WFM1-2 ansible_host=172.18.5.31
WFM1-3 ansible_host=10.250.100.159
WFM1-4 ansible_host=10.250.100.152
WFM2-1 ansible_host=10.250.100.158
WFM2-1 ansible_host=10.250.100.202
WFM2-2 ansible_host=10.250.100.160
WFM2-3 ansible_host=10.250.100.161
WFM2-4 ansible_host=10.250.100.153

[PEAJES_ELECTRONICOS]
FPSRV0101 ansible_host=172.18.166.226

[PORVENIR]
PRV1133 ansible_host=10.61.28.119
PRV1134 ansible_host=10.61.28.72
PRV1135 ansible_host=10.61.28.71

[PREVISORA]
PR0980VR5_3G ansible_host=172.16.13.57
pr0980vr5_3g ansible_host=172.16.13.57
PRDPDVWPISOLAP ansible_host=172.16.12.25
PRDPFTELIPTAR ansible_host=172.127.0.9
prdppvlpcotzap ansible_host=172.26.0.1
prdpvlpagesap ansible_host=192.168.70.30
prdpvlpccenap ansible_host=172.16.13.230
PRDPVLPCTXAP ansible_host=172.16.128.197
PRDPVLPOIGAP ansible_host=192.168.122.1
PRDPVLPSFTPFS ansible_host=10.110.41.235
PRDPVLPSOCAP ansible_host=192.168.60.5
prdpvlptraap1 ansible_host=172.16.13.229
PRDPVLPTRAAP2 ansible_host=192.168.70.27
PRDPVLTAGESAP ansible_host=172.210.0.24
PRDPVLTCCENAP
PRDPVLTCCENAP ansible_host=172.17.0.1
PRDPVLTCCENAP ansible_host=172.210.0.23
PRDPVLTCOTAP ansible_host=172.210.0.151
PRDPVLTIPSAAP ansible_host=172.210.0.120
PRDPVLTOIGAP ansible_host=172.210.0.13
PRDPVLTSICAP1 ansible_host=172.16.13.181
PRDPVLTTRAAP ansible_host=172.210.0.15
PRDPVWDS3GR2AP2 ansible_host=172.210.0.122
PRDPVWDS3GR2IN2 ansible_host=172.210.0.123
PRDPVWDS3GR2INT ansible_host=172.210.0.167
PRDPVWDS3GR2PE2 ansible_host=172.210.0.124
PRDPVWPAPRWS ansible_host=172.16.13.132
PRDPVWPAPRWS1 ansible_host=172.16.13.150
PRDPVWPAPRWS2 ansible_host=172.16.13.116
PRDPVWPARA8AP ansible_host=172.16.12.112
PRDPVWPARA8AP ansible_host=172.210.0.112
PRDPVWPCONTACAP ansible_host=172.16.13.213
PRDPVWPCONTACAPv ansible_host=172.16.13.213
PRDPVWPCPRESAP ansible_host=100.66.0.99
PRDPVWPCPRESAP ansible_host=172.16.13.130
PRDPVWPCTLAP ansible_host=172.16.13.190
PRDPVWPCWINBD ansible_host=172.16.12.163
PRDPVWPEXCHAP1 ansible_host=172.16.12.222
PRDPVWPEXCHAP1v ansible_host=172.16.12.222
PRDPVWPFACELWB2 ansible_host=192.168.70.12
PRDPVWPFTECAP ansible_host=172.16.13.30
PRDPVWPGITAP ansible_host=172.16.12.44
PRDPVWPINVEAP ansible_host=172.16.12.235
PRDPVWPMASAP ansible_host=172.16.13.142
PRDPVWPNIIFWS ansible_host=172.16.12.123
PRDPVWPONBAP ansible_host=172.16.12.156
PRDPVWPONBAP ansible_host=172.16.13.31
PRDPVWPONBAP1 ansible_host=172.16.13.219
PRDPVWPONBAP2 ansible_host=172.16.12.228
PRDPVWPONBWB ansible_host=172.16.12.157
PRDPVWPONBWB1 ansible_host=172.16.13.74
PRDPVWPONBWB2 ansible_host=172.16.12.227
PRDPVWPPAGOAP ansible_host=172.16.13.48
PRDPVWPRELAYAP ansible_host=172.16.12.120
PRDPVWPS3GR2AP2 ansible_host=172.16.12.206
PRDPVWPS3GR2AP3 ansible_host=172.16.12.175
PRDPVWPS3GR2AP9 ansible_host=172.210.0.84
PRDPVWPS3GR2INT ansible_host=172.16.12.207
PRDPVWPS3GR2PE1 ansible_host=172.16.12.203
PRDPVWPS3GR2PE2 ansible_host=172.210.0.73
PRDPVWPS3GR2PE6 ansible_host=172.210.0.101
PRDPVWPSARLFRB1 ansible_host=172.210.0.74
PRDPVWPSARLFWK1 ansible_host=172.16.12.23
PRDPVWPSARLFWK2 ansible_host=172.210.0.75
PRDPVWPTREPAP ansible_host=172.16.12.27
PRDPVWPVARAP ansible_host=172.16.13.126
PRDPVWPVOZIPAP1 ansible_host=172.127.0.10
PRDPVWTARAAP ansible_host=172.210.0.112
PRDPVWTCMASAP ansible_host=172.210.0.66
PRDPVWTCPRESAP ansible_host=172.210.0.164
PRDPVWTFACELAP1 ansible_host=172.210.0.131
PRDPVWTFACELAP2 ansible_host=172.210.0.132
PRDPVWTFACELWB1 ansible_host=172.210.0.11
PRDPVWTMASAPC2 ansible_host=172.210.0.106
PRDPVWTONBWB ansible_host=172.210.0.118
PRDPVWTS3GAUTAP ansible_host=172.210.0.78
PRDPVWTS3GR2AP1 ansible_host=172.210.0.100
PRDPVWTS3GR2INT ansible_host=172.210.0.171
PRDPVWTS3GR2PE1 ansible_host=172.210.0.85
PRDPVWTSICAP2 ansible_host=172.16.13.182
PRDPVWTVARAP ansible_host=172.210.0.61
PRPRINTSRV ansible_host=172.16.60.4
ZBHB00703 ansible_host=172.210.0.122
ZBHB402 ansible_host=172.27.130.145
ZBHB501 ansible_host=100.65.43.203

[TENNIS]
appy2prod ansible_host=172.18.20.152
appy3dev ansible_host=172.18.20.132
appy3prod ansible_host=172.18.20.134
ftpy2prod ansible_host=172.18.20.144
nowapp1 ansible_host=100.66.17.216
nowapp2 ansible_host=100.66.17.217
t270db2 ansible_host=10.110.46.54

# ==============================================================================
# 2. GRUPOS POR SISTEMA OPERATIVO
# ==============================================================================

[linux_servers]
ANTHOLOGY1
ANTHOLOGY2
apploadbalancebta11
apploadbalancebta21
appy2prod
appy3dev
appy3prod
ath-app1-1
ath-app1-2
CACTUS1
CIMWAS1-1
CIMWAS2-2
cm-was-bancobog1-1
cm-was-bancobog2-1
cm-was-ccc1-1
cm-was-ccc2-1
cm-was-GVP-aval-1-1
cm-was-gvp-aval-1-2
cm-was-gvp-aval-1-3
cm-was-GVP-aval-2-1
cm-was-GVP-aval-2-2
cm-was-GVP-aval-2-3
cm-was-gvp-ivr-banco-bogota-1-1
cm-was-gvp-ivr-banco-bogota-2-1
cm-was-ORS-aval-1-1
cm-was-ORS-aval-1-2
cm-was-ORS-aval-1-3
cm-was-ORS-aval-2-1
cm-was-ORS-aval-2-2
cm-was-ORS-aval-2-3
desarrollos1
desarrollos2
FILESERVER1
FILESERVER2
ftpy2prod
GMS1-1
GMS1-3
GMS2-1
GMS2-3
gvpwas1-1
gvpwas2-1
HEY0028
HTCC1_1
HTCC1_2
HTCC2_1
nowapp1
nowapp2
OMH0043_Tomcat
prdppvlpcotzap
prdpvlpagesap
prdpvlpccenap
PRDPVLPCTXAP
PRDPVLPOIGAP
PRDPVLPSFTPFS
PRDPVLPSOCAP
prdpvlptraap1
PRDPVLPTRAAP2
PRDPVLTAGESAP
PRDPVLTCCENAP
PRDPVLTCOTAP
PRDPVLTIPSAAP
PRDPVLTOIGAP
PRDPVLTSICAP1
PRDPVLTTRAAP
PRV1133
PRV1134
PRV1135
sv-villa-1-1
sv-villa-2-1
t270db2
ZBHB402
ZBHB501

[windows_servers]
CENTAURI
CIMWAS1-1
FORMULARIOSSERVER1
FORMULARIOSSERVER2
FPSRV0101
GADMIN1-1
GIM1-2-TFM1301
GIM2-2-TFM1307
LABMCPGIR1
PR0980VR5_3G
PRCIMWAS1-1
PRDPDVWPISOLAP
PRDPFTELIPTAR
PRDPVWDS3GR2AP2
PRDPVWDS3GR2IN2
PRDPVWDS3GR2INT
PRDPVWDS3GR2PE2
PRDPVWPAPRWS
PRDPVWPAPRWS1
PRDPVWPAPRWS2
PRDPVWPARA8AP
PRDPVWPCONTACAP
PRDPVWPCONTACAPv
PRDPVWPCPRESAP
PRDPVWPCTLAP
PRDPVWPCWINBD
PRDPVWPEXCHAP1
PRDPVWPEXCHAP1v
PRDPVWPFACELWB2
PRDPVWPFTECAP
PRDPVWPGITAP
PRDPVWPINVEAP
PRDPVWPMASAP
PRDPVWPNIIFWS
PRDPVWPONBAP
PRDPVWPONBAP1
PRDPVWPONBAP2
PRDPVWPONBWB
PRDPVWPONBWB1
PRDPVWPONBWB2
PRDPVWPPAGOAP
PRDPVWPRELAYAP
PRDPVWPS3GR2AP2
PRDPVWPS3GR2AP3
PRDPVWPS3GR2AP9
PRDPVWPS3GR2INT
PRDPVWPS3GR2PE1
PRDPVWPS3GR2PE2
PRDPVWPS3GR2PE6
PRDPVWPSARLFRB1
PRDPVWPSARLFWK1
PRDPVWPSARLFWK2
PRDPVWPTREPAP
PRDPVWPVARAP
PRDPVWPVOZIPAP1
PRDPVWTARAAP
PRDPVWTCMASAP
PRDPVWTCPRESAP
PRDPVWTFACELAP1
PRDPVWTFACELAP2
PRDPVWTFACELWB1
PRDPVWTMASAPC2
PRDPVWTONBWB
PRDPVWTS3GAUTAP
PRDPVWTS3GR2AP1
PRDPVWTS3GR2INT
PRDPVWTS3GR2PE1
PRDPVWTSICAP2
PRDPVWTVARAP
PRPRINTSRV
SPOTLIGHT
TFM3053
WFM1-1
WFM1-2
WFM1-3
WFM1-4
WFM2-1
WFM2-2
WFM2-3
WFM2-4
ZBHB00703

# ==============================================================================
# 3. VARIABLES DE TRANSPORTE WINDOWS (WinRM)
# ==============================================================================
[windows_servers:vars]
ansible_connection=winrm
ansible_winrm_server_cert_validation=ignore
ansible_winrm_transport=ntlm
